### ISSUE TITLE
hasDescription  prop DOM element error al aparecer el mensaje de toast

### ISSUE THREAD

**Issue by devodla** [onlyreynaldo/gobarber-web-eleventh#2]
Warning: React does not recognize the `hasDescription` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hasdescription` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ForwardRef)
    in ForwardRef (created by Styled(Component))
    in Styled(Component) (at Toast/index.tsx:38)
    in Toast (at ToatsContainer/index.tsx:26)
    in div (created by styled.div)
    in styled.div (at ToatsContainer/index.tsx:24)
    in ToatsContainer (at toast.tsx:46)
    in ToastProvider (at hooks/index.tsx:8)
    in AuthProvider (at hooks/index.tsx:7)
    in AppProvider (at App.tsx:12)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.tsx:11)
    in App (at src/index.tsx:7)
    in StrictMode (at src/index.tsx:6)

**Comment by hgcordeiro** [comment]
You can solve this issue by using hasDescription prop as a transient prop. To do it, just add '$' to the prop name ($hasDescription).
This way you can prevent props cosumed by styled components being rendered to the DOM.
You can read about it here: [https://styled-components.com/docs/api#transient-props](url)

**Comment by devodla** [comment]
Thanks @hgcordeiro
